import Link from "next/link";
import { notFound } from "next/navigation";
import { Paperclip, Pencil } from "lucide-react";
import { db } from "@/server/db/client";
import { getCurrentUser } from "@/modules/auth";
import { StatusBadge } from "@/components/status-badge";
import { Card } from "@/components/ui/card";
import { canEditDraft } from "@/modules/change-requests/authorization";
import { removeAttachment, submitExistingRequest, uploadAttachment } from "@/modules/change-requests/actions";
import type { ChangeRequestStatusKey } from "@/modules/workflow/status";

const tabs=["Übersicht","Freigaben","Technische Prüfung","AVOR","Einkauf","Aufgaben","Anhänge","Kommentare","Historie"];
export default async function RequestDetailPage({params,searchParams}:PageProps<"/change-requests/[id]">){const {id}=await params;const query=await searchParams;const tab=typeof query.tab==="string"?query.tab:"Übersicht";const user=await getCurrentUser();const request=await db.changeRequest.findUnique({where:{id},include:{applicant:true,machineType:true,reasons:{include:{changeReason:true}},attachments:{where:{deletedAt:null},orderBy:{uploadedAt:"desc"}},auditEvents:{include:{user:true},orderBy:{timestamp:"desc"}}}});if(!request)notFound();const editable=canEditDraft(user,request);const date=(d:Date)=>new Intl.DateTimeFormat("de-CH",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Zurich"}).format(d);
return <div><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><p className="font-mono text-sm font-semibold text-[#175f91]">{request.number}</p><StatusBadge status={request.status as ChangeRequestStatusKey}/></div><h1 className="mt-2 text-2xl font-bold text-slate-950">{request.title||"Unbenannter Entwurf"}</h1><p className="mt-1 text-sm text-slate-500">{request.machineType?.code??"Kein Maschinentyp"} · {request.applicant.name}</p></div>{editable&&<div className="flex gap-2"><Link href={`/change-requests/${id}/edit`} className="flex items-center gap-2 rounded-md border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold"><Pencil className="size-4"/>Bearbeiten</Link><form action={submitExistingRequest.bind(null,id)}><button className="rounded-md bg-[#175f91] px-4 py-2.5 text-sm font-semibold text-white">Einreichen</button></form></div>}</div>
<div className="mb-5 overflow-x-auto border-b border-slate-200"><nav className="flex min-w-max gap-5">{tabs.map(t=><Link key={t} href={`?tab=${encodeURIComponent(t)}`} className={`border-b-2 px-1 pb-3 text-sm font-medium ${tab===t?"border-[#175f91] text-[#175f91]":"border-transparent text-slate-500"}`}>{t}</Link>)}</nav></div>
{tab==="Übersicht"?<div className="grid gap-5 xl:grid-cols-[2fr_1fr]"><Card className="p-6"><h2 className="font-semibold">Antragsdetails</h2><dl className="mt-5 grid gap-5 md:grid-cols-2"><Item l="Artikel-/Baugruppennummer" v={request.articleNumber}/><Item l="Artikel-/Baugruppenbezeichnung" v={request.articleDescription}/><div className="md:col-span-2"><dt className="text-xs font-medium uppercase text-slate-500">Änderungsgrund</dt><dd className="mt-1 text-sm">{request.reasons.map(r=>r.changeReason.label).join(", ")||"–"}</dd></div><div className="md:col-span-2"><dt className="text-xs font-medium uppercase text-slate-500">Beschreibung und Begründung</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{request.description||"–"}</dd></div></dl></Card><Card className="p-6"><h2 className="font-semibold">Zeitangaben</h2><dl className="mt-5 space-y-4"><Item l="Erstellt" v={date(request.createdAt)}/><Item l="Zuletzt aktualisiert" v={date(request.updatedAt)}/>{request.submittedAt&&<Item l="Eingereicht" v={date(request.submittedAt)}/>}</dl></Card></div>:tab==="Anhänge"?<Card className="p-6"><h2 className="font-semibold">Anhänge</h2>{editable&&<form action={uploadAttachment.bind(null,id)} className="mt-4 flex flex-wrap items-center gap-3"><input required name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx" className="text-sm"/><button className="rounded-md bg-[#175f91] px-3 py-2 text-sm font-semibold text-white">Hochladen</button></form>}<div className="mt-5 divide-y divide-slate-100">{request.attachments.map(a=><div key={a.id} className="flex items-center justify-between gap-3 py-3"><a href={`/change-requests/${id}/attachments/${a.id}`} className="flex items-center gap-2 text-sm font-medium text-[#175f91]"><Paperclip className="size-4"/>{a.originalName}</a>{editable&&<form action={removeAttachment.bind(null,a.id)}><button className="text-sm text-red-700">Entfernen</button></form>}</div>)}{!request.attachments.length&&<p className="py-4 text-sm text-slate-500">Keine Anhänge vorhanden.</p>}</div></Card>:tab==="Historie"?<Card className="divide-y divide-slate-100">{request.auditEvents.map(e=><div key={e.id} className="p-5"><p className="text-sm font-medium">{e.summary}</p><p className="mt-1 text-xs text-slate-500">{date(e.timestamp)} · {e.user?.name??"System"} · {e.action}</p></div>)}{!request.auditEvents.length&&<p className="p-6 text-sm text-slate-500">Keine Einträge vorhanden.</p>}</Card>:<Card className="p-10 text-center text-sm text-slate-500">Diese Funktion wird in einer späteren Phase implementiert.</Card>}</div>}
function Item({l,v}:{l:string;v:string|null|undefined}){return <div><dt className="text-xs font-medium uppercase text-slate-500">{l}</dt><dd className="mt-1 text-sm text-slate-900">{v||"–"}</dd></div>}
