import { describe, expect, it } from "vitest";
import { buildPersonalInbox, filterInbox, type RequestRef, type TaskRef } from "./domain";

const request=(overrides:Partial<RequestRef>={}):RequestRef=>({id:"cr-1",number:"CR-2026-031",title:"Riemenspanner",status:"UNDER_REVIEW",approvalCycle:2,finalReviewCycle:1,machineType:{code:"CB1"},approvals:[{type:"AVOR",status:"PENDING",cycle:2},{type:"TECHNICAL",status:"PENDING",cycle:2}],finalApprovals:[],technicalReview:null,avorImpactReview:null,purchasingReview:null,...overrides});
const task=(overrides:Partial<TaskRef>={}):TaskRef=>({id:"task-1",title:"Zeichnung aktualisieren",status:"OPEN",priority:"HIGH",dueDate:new Date("2026-08-20T00:00:00+02:00"),changeRequest:{id:"cr-1",number:"CR-2026-031",title:"Riemenspanner",status:"UNDER_REVIEW",machineType:{code:"CB1"}},...overrides});
const inbox=(roles:("EMPLOYEE"|"AVOR"|"TECHNICAL"|"ADMINISTRATOR")[],requests:RequestRef[]=[request()],tasks:TaskRef[]=[])=>buildPersonalInbox({roles,requests,tasks,now:new Date("2026-08-21T12:00:00+02:00")});

describe("Persönliche Arbeits-Inbox",()=>{
  it("zeigt nur die offene AVOR-Freigabe der aktuellen Runde",()=>{expect(inbox(["AVOR"])[0].action).toBe("AVOR-Freigabe erforderlich");expect(inbox(["AVOR"],[request({approvals:[{type:"AVOR",status:"APPROVED",cycle:2},{type:"AVOR",status:"PENDING",cycle:1},{type:"TECHNICAL",status:"PENDING",cycle:2}]})]).some(i=>i.action.includes("AVOR-Freigabe"))).toBe(false)});
  it("zeigt AVOR-Prüfung und Einkauf nur solange sie offen und bearbeitbar sind",()=>{const source=request({status:"PURCHASING_PROCUREMENT",avorImpactReview:null,purchasingReview:null});const actions=inbox(["AVOR"],[source]).map(i=>i.action);expect(actions).toContain("AVOR-Prüfung durchführen");expect(actions).toContain("Einkauf / Beschaffung bearbeiten");expect(inbox(["AVOR"],[request({...source,avorImpactReview:{completed:true},purchasingReview:{completed:true}})]).map(i=>i.action)).not.toContain("Einkauf / Beschaffung bearbeiten")});
  it("zeigt die offene AVOR-Abschlussfreigabe nur in der aktuellen Abschlussrunde",()=>{const source=request({status:"FINAL_REVIEW",finalReviewCycle:2,avorImpactReview:{completed:true},finalApprovals:[{type:"AVOR",cycle:1}]});expect(inbox(["AVOR"],[source]).map(i=>i.action)).toContain("AVOR-Abschlussfreigabe erforderlich");expect(inbox(["AVOR"],[request({...source,finalApprovals:[{type:"AVOR",cycle:2}]})]).map(i=>i.action)).not.toContain("AVOR-Abschlussfreigabe erforderlich")});
  it("zeigt die technische Freigabe der aktuellen Runde",()=>expect(inbox(["TECHNICAL"])[0].action).toBe("Technische Freigabe erforderlich"));
  it("zeigt Technikprüfung bereits bei offener AVOR-Freigabe und entfernt sie nach Abschluss",()=>{const source=request({approvals:[{type:"AVOR",status:"PENDING",cycle:2},{type:"TECHNICAL",status:"APPROVED",cycle:2}]});expect(inbox(["TECHNICAL"],[source]).map(i=>i.action)).toContain("Technische Prüfung durchführen");expect(inbox(["TECHNICAL"],[request({...source,technicalReview:{completed:true}})]).map(i=>i.action)).not.toContain("Technische Prüfung durchführen")});
  it("zeigt die technische Abschlussfreigabe nur in der aktuellen Runde",()=>{const source=request({status:"FINAL_REVIEW",approvals:[{type:"TECHNICAL",status:"APPROVED",cycle:2}],technicalReview:{completed:true},finalReviewCycle:3,finalApprovals:[{type:"TECHNICAL",cycle:2}]});expect(inbox(["TECHNICAL"],[source]).map(i=>i.action)).toContain("Technische Abschlussfreigabe erforderlich")});
  it("zeigt Mitarbeitern nur zugewiesene offene Aufgaben",()=>{const items=inbox(["EMPLOYEE"],[request()],[task()]);expect(items).toHaveLength(1);expect(items[0]).toMatchObject({kind:"TASK",action:"Zeichnung aktualisieren",overdue:true});expect(inbox(["EMPLOYEE"],[],[task({status:"DONE"})])).toHaveLength(0)});
  it("kombiniert Dualrollen ohne doppelte Business-Aktionen",()=>{const items=inbox(["AVOR","TECHNICAL"]);expect(items.map(i=>i.action)).toEqual(expect.arrayContaining(["AVOR-Freigabe erforderlich","Technische Freigabe erforderlich"]));expect(new Set(items.map(i=>i.id)).size).toBe(items.length)});
  it("zeigt Administratoren ohne explizite Fachrolle keinen globalen Workflow-Backlog",()=>expect(inbox(["ADMINISTRATOR"])).toHaveLength(0));
  it("unterdrückt alle Aktionen geschlossener Anträge",()=>{const closed=request({status:"CLOSED"});expect(inbox(["AVOR","TECHNICAL"],[closed],[task({changeRequest:{...task().changeRequest,status:"CLOSED"}})])).toHaveLength(0)});
  it("filtert Überfälligkeit ausschliesslich aus Aufgaben",()=>{const items=inbox(["AVOR"],[request()],[task()]);expect(filterInbox(items,"OVERDUE")).toHaveLength(1);expect(filterInbox(items,"OVERDUE")[0].kind).toBe("TASK")});
  it("verlinkt jede Aktion direkt zum relevanten Tab und verschwindet nach Erledigung",()=>{const approval=inbox(["AVOR"])[0];expect(approval.href).toBe("/change-requests/cr-1?tab=Freigaben");expect(inbox(["AVOR"],[request({approvals:[{type:"AVOR",status:"APPROVED",cycle:2},{type:"TECHNICAL",status:"PENDING",cycle:2}]})]).some(i=>i.id===approval.id)).toBe(false);expect(inbox(["EMPLOYEE"],[],[task()])[0].href).toContain("?tab=Aufgaben#task-task-1")});
});
