"use server";

import {revalidatePath} from "next/cache";
import {db} from "@/server/db/client";
import {getCurrentUser} from "@/modules/auth";
import {requirePermission} from "@/modules/authorization/permissions";
import {canEditTechnicalReview,completionMetadata,reopenedMetadata,reopenSchema,technicalReviewAudit,technicalReviewCompletionSchema,technicalReviewDraftSchema,type ReviewAnswerKey} from "./domain";
import {applyImplementationReviewTransition} from "@/modules/implementation-workflow/transition";

export type TechnicalReviewActionState={errors?:Record<string,string[]>;message?:string;success?:string};
const answer=(v:FormDataEntryValue|null):ReviewAnswerKey|null=>v==="YES"||v==="NO"||v==="NOT_RELEVANT"?v:null;
function input(form:FormData){return {operatingSafety:answer(form.get("operatingSafety")),operatingSafetyComment:String(form.get("operatingSafetyComment")??""),interchangeability:answer(form.get("interchangeability")),interchangeabilityComment:String(form.get("interchangeabilityComment")??""),affectsOthers:answer(form.get("affectsOthers")),affectedItemsExplanation:String(form.get("affectedItemsExplanation")??""),existingArticlesUsable:answer(form.get("existingArticlesUsable")),existingArticlesAction:String(form.get("existingArticlesAction")??""),nextSteps:String(form.get("nextSteps")??""),implementationNotes:String(form.get("implementationNotes")??""),sparePartsCatalogueUpdated:answer(form.get("sparePartsCatalogueUpdated")),sparePartsCatalogueComment:String(form.get("sparePartsCatalogueComment")??""),manufacturingDocsUpdated:answer(form.get("manufacturingDocsUpdated")),manufacturingDocsComment:String(form.get("manufacturingDocsComment")??"")}}
const gateSelect={status:true,approvalCycle:true,approvals:{where:{type:"TECHNICAL" as const},select:{cycle:true,status:true}}} as const;
function technicalGate(request:{status:string;approvalCycle:number;approvals:Array<{cycle:number;status:string}>}){return {status:request.status,technicalApprovalStatus:request.approvals.find((approval)=>approval.cycle===request.approvalCycle)?.status}}

export async function saveTechnicalReview(requestId:string,_state:TechnicalReviewActionState,form:FormData):Promise<TechnicalReviewActionState>{
  const user=await getCurrentUser();requirePermission(user,"TECHNICAL_REVIEW_EDIT");const request=await db.changeRequest.findUniqueOrThrow({where:{id:requestId},select:{...gateSelect,technicalReview:{select:{completed:true}}}});if(!canEditTechnicalReview(user,technicalGate(request)))return {message:"Die technische Prüfung ist erst nach der Technikfreigabe der aktuellen Freigaberunde bearbeitbar."};if(request.technicalReview?.completed)return {message:"Eine abgeschlossene technische Prüfung muss zuerst erneut geöffnet werden."};
  const intent=String(form.get("intent"));const parsed=(intent==="complete"?technicalReviewCompletionSchema:technicalReviewDraftSchema).safeParse(input(form));if(!parsed.success)return {errors:parsed.error.flatten().fieldErrors};
  await db.$transaction(async tx=>{const current=await tx.changeRequest.findUniqueOrThrow({where:{id:requestId},select:{...gateSelect,avorImpactReview:{select:{completed:true}}}});if(!canEditTechnicalReview(user,technicalGate(current)))throw new Error("Die Technikfreigabe der aktuellen Freigaberunde liegt nicht mehr vor.");const existing=await tx.technicalReview.findUnique({where:{changeRequestId:requestId},select:{id:true,completed:true}});if(existing?.completed)throw new Error("Eine abgeschlossene technische Prüfung muss zuerst erneut geöffnet werden.");const data={...parsed.data,operatingSafetyComment:parsed.data.operatingSafetyComment||null,interchangeabilityComment:parsed.data.interchangeabilityComment||null,affectedItemsExplanation:parsed.data.affectedItemsExplanation||null,existingArticlesAction:parsed.data.existingArticlesAction||null,nextSteps:parsed.data.nextSteps||null,implementationNotes:parsed.data.implementationNotes||null,sparePartsCatalogueComment:parsed.data.sparePartsCatalogueComment||null,manufacturingDocsComment:parsed.data.manufacturingDocsComment||null,...(intent==="complete"?completionMetadata(user.id):{})};const review=await tx.technicalReview.upsert({where:{changeRequestId:requestId},create:{changeRequestId:requestId,...data},update:data});const audit=technicalReviewAudit(user.name,intent==="complete"?"COMPLETED":existing?"SAVED":"STARTED");await tx.auditEvent.create({data:{changeRequestId:requestId,userId:user.id,...audit,entityType:"TechnicalReview",entityId:review.id}});await applyImplementationReviewTransition(tx,{requestId,currentStatus:current.status,technicalCompleted:intent==="complete",avorCompleted:Boolean(current.avorImpactReview?.completed),userId:user.id})},{isolationLevel:"Serializable"});
  revalidatePath(`/change-requests/${requestId}`);return {success:intent==="complete"?"Technische Prüfung abgeschlossen.":"Technische Prüfung gespeichert."};
}

export async function reopenTechnicalReview(requestId:string,_state:TechnicalReviewActionState,form:FormData):Promise<TechnicalReviewActionState>{
  const user=await getCurrentUser();requirePermission(user,"TECHNICAL_REVIEW_EDIT");const parsed=reopenSchema.safeParse({reason:form.get("reason")});if(!parsed.success)return {message:parsed.error.issues[0].message};
  const request=await db.changeRequest.findUniqueOrThrow({where:{id:requestId},select:gateSelect});if(!canEditTechnicalReview(user,technicalGate(request)))return {message:"Die technische Prüfung ist erst nach der Technikfreigabe der aktuellen Freigaberunde bearbeitbar."};
  await db.$transaction(async tx=>{const current=await tx.changeRequest.findUniqueOrThrow({where:{id:requestId},select:gateSelect});if(!canEditTechnicalReview(user,technicalGate(current)))throw new Error("Die Technikfreigabe der aktuellen Freigaberunde liegt nicht mehr vor.");const review=await tx.technicalReview.findUniqueOrThrow({where:{changeRequestId:requestId}});const changed=await tx.technicalReview.updateMany({where:{id:review.id,completed:true},data:reopenedMetadata()});if(changed.count!==1)throw new Error("Die technische Prüfung ist bereits geöffnet.");const audit=technicalReviewAudit(user.name,"REOPENED",parsed.data.reason);await tx.auditEvent.create({data:{changeRequestId:requestId,userId:user.id,...audit,entityType:"TechnicalReview",entityId:review.id,details:{reason:parsed.data.reason,previousCompletedById:review.completedById,previousCompletedAt:review.completedAt?.toISOString()}}});});
  revalidatePath(`/change-requests/${requestId}`);return {success:"Technische Prüfung erneut geöffnet."};
}
