import { z } from "zod";
import type { AuthUser } from "@/modules/auth";

export const REVIEW_ANSWERS=["YES","NO","NOT_RELEVANT"] as const;
export type ReviewAnswerKey=(typeof REVIEW_ANSWERS)[number];
export const REVIEW_LABELS:Record<ReviewAnswerKey,string>={YES:"Ja",NO:"Nein",NOT_RELEVANT:"Nicht relevant"};
const answer=z.enum(REVIEW_ANSWERS).nullable();
export const technicalReviewDraftSchema=z.object({operatingSafety:answer,operatingSafetyComment:z.string().trim().max(4000),interchangeability:answer,interchangeabilityComment:z.string().trim().max(4000),affectsOthers:answer,affectedItemsExplanation:z.string().trim().max(8000),existingArticlesUsable:answer,existingArticlesAction:z.string().trim().max(8000),nextSteps:z.string().trim().max(8000),implementationNotes:z.string().trim().max(8000),sparePartsCatalogueUpdated:answer,sparePartsCatalogueComment:z.string().trim().max(4000),manufacturingDocsUpdated:answer,manufacturingDocsComment:z.string().trim().max(4000)});
export const technicalReviewCompletionSchema=technicalReviewDraftSchema.superRefine((v,c)=>{if(!v.operatingSafety)c.addIssue({code:"custom",path:["operatingSafety"],message:"Bitte die Betriebssicherheit beurteilen."});if(v.operatingSafety==="NO"&&!v.operatingSafetyComment)c.addIssue({code:"custom",path:["operatingSafetyComment"],message:"Bitte die erforderlichen Massnahmen zur Betriebssicherheit beschreiben."});if(!v.interchangeability)c.addIssue({code:"custom",path:["interchangeability"],message:"Bitte die Austauschbarkeit beurteilen."});if(v.interchangeability==="NO"&&!v.interchangeabilityComment)c.addIssue({code:"custom",path:["interchangeabilityComment"],message:"Bitte die Auswirkungen auf die Austauschbarkeit beschreiben."});if(!v.affectsOthers)c.addIssue({code:"custom",path:["affectsOthers"],message:"Bitte die Auswirkungen auf weitere Artikel, Maschinen oder Baugruppen beurteilen."});if(v.affectsOthers==="YES"&&!v.affectedItemsExplanation)c.addIssue({code:"custom",path:["affectedItemsExplanation"],message:"Bitte die Auswirkungen auf weitere Artikel, Maschinen oder Baugruppen beschreiben."});if(!v.existingArticlesUsable)c.addIssue({code:"custom",path:["existingArticlesUsable"],message:"Bitte die Verwendung bestehender Artikel beurteilen."});if(v.existingArticlesUsable==="NO"&&!v.existingArticlesAction)c.addIssue({code:"custom",path:["existingArticlesAction"],message:"Bitte beschreiben, was mit bestehenden Artikeln geschieht."});if(!v.nextSteps)c.addIssue({code:"custom",path:["nextSteps"],message:"Bitte die nächsten Schritte erfassen."});if(!v.sparePartsCatalogueUpdated)c.addIssue({code:"custom",path:["sparePartsCatalogueUpdated"],message:"Bitte den Status des ET-Katalogs erfassen."});if(!v.manufacturingDocsUpdated)c.addIssue({code:"custom",path:["manufacturingDocsUpdated"],message:"Bitte den Status der Fertigungsunterlagen erfassen."})});
const allowedStatuses=new Set(["APPROVED_FOR_IMPLEMENTATION","IMPLEMENTATION","AVOR_PRODUCTION_PREPARATION","PURCHASING_PROCUREMENT","FINAL_REVIEW"]);
export function technicalReviewAvailable(requestStatus:string){return allowedStatuses.has(requestStatus)}
export function canEditTechnicalReview(user:Pick<AuthUser,"roles">,requestStatus:string){return technicalReviewAvailable(requestStatus)&&(user.roles.includes("TECHNICAL")||user.roles.includes("ADMINISTRATOR"))}
export function technicalReviewState(review?:{completed:boolean}|null){return !review?"NOT_STARTED" as const:review.completed?"COMPLETED" as const:"IN_PROGRESS" as const}
export const reopenSchema=z.object({reason:z.string().trim().min(1,"Bitte begründen Sie die erneute Öffnung.").max(2000)});
export function completionMetadata(userId:string,now=new Date()){return {completed:true,completedById:userId,completedAt:now}}
export function reopenedMetadata(){return {completed:false,completedById:null,completedAt:null}}
export function technicalReviewAudit(userName:string,event:"STARTED"|"SAVED"|"COMPLETED"|"REOPENED",reason?:string){const summaries={STARTED:`${userName} hat die technische Prüfung begonnen.`,SAVED:`${userName} hat die technische Prüfung aktualisiert.`,COMPLETED:`${userName} hat die technische Prüfung abgeschlossen.`,REOPENED:`${userName} hat die technische Prüfung erneut geöffnet. Grund: ${reason}`};return {action:`TECHNICAL_REVIEW_${event}`,summary:summaries[event]}}
